#!/bin/bash
function usage {
  echo "Usage $0 <number_of_processes> [<number_of_tasks>]"
  exit
}

if [ ! -e queueTimingTest.php ]
then
  echo "Call from the directory that contains this script.\n" >&2
  usage
fi

qty=$1
if [[ "$qty" -lt 1 ]]
then
  echo "Call with at least 1 process!" >&2
  usage
  exit
fi

if [[ ! -z "$2" ]]
then
  tasks=$2
else
  tasks=10
fi

# Init log file
echo "Queue test with $qty parallel processes and $tasks tasks running at" $(date -Is) |tee test-result.log

for id in $(seq $qty)
do php queueTimingTest.php $id $qty $tasks &
done | tee -a test-result.log
wait

# Check all tasks ran.
there_were_errors=
for id in $(seq $tasks)
do
  n=$(grep "Task $id running" test-result.log | wc -l)
  if [ "$n" != "1" ]
  then
    echo "ERROR: Task $id ran $n times" |tee -a test-result.log
    there_were_errors=yes
  fi
done
[[ -z "$there_were_errors" ]] && echo "Each task ran once." | tee -a test-result.log
